# Change these first
owner: darwinhk
repo: status

sites:
  - name: #网站# 达尔文主页(亚洲/Asia)
    url: https://www.darwin.hk
  - name: #网站# 达尔文主页(美国/U.S)
    url: https://darwin.hk
  - name: #网站# 授权用户控制台
    url: https://dash.darwin.hk
  - name: #接口# 数字许可权利中心
    url: https://account.darwin.hk
  - name: #服务# 云雷达中转服务
    url: http://cloudradar-cnsh.darwin.hk:27075
  - name: #订阅# CS:GO Premium
    url: https://prd-status-csgo-premium.check.darwin.hk
  - name: #订阅# CS:GO CloudRadar
    url: https://prd-status-csgo-cloudradar.check.darwin.hk
  - name: #订阅# PUBG Premium
    url: https://prd-status-pubg-premium.check.darwin.hk


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.darwin.hk
  # baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: 达尔文服务实时状态
  introTitle: "**服务状态**"
  introMessage: **达尔文DARWIN**线上服务实时状态
  navbar:
    - title: 控制台
      href: https://dash.darwin.hk/
    - title: 购买授权
      href: https://www.darwin.hk/pay.html

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
