# Change these first
owner: darwinhk
repo: status

sites:
  - name: 主页(Asia)
    url: https://www.darwin.hk
  - name: 主页(US/Source)
    url: https://darwin.hk
  - name: 数字许可
    url: https://account.darwin.hk
  - name: 控制台(用户中心)
    url: https://dash.darwin.hk

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.darwin.hk
  # baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: 达尔文服务实时状态
  introTitle: "**达尔文Darwin** 实时服务状态."
  introMessage: 您可以通过此页面查看达尔文相关服务的 **实时状态** ；当然，这可能会有大约5分钟左右的数据延迟。
  navbar:
    - title: 实时状态
      href: /
    - title: 授权订阅
      href: https://www.darwin.hk/pay.html

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
