# Change these first
owner: darwinhk
repo: status

sites:
  - name: "#网站# 达尔文主页(亚洲/Asia)"
    url: https://www.darwin.hk
  - name: "#网站# 达尔文主页(美国/U.S)"
    url: https://darwin.hk
  - name: "#网站# 授权用户控制台"
    url: https://dash.darwin.hk
  - name: "#服务# 数字许可权利管理"
    url: https://account.darwin.hk
  - name: "#服务# 云雷达中转服务"
    url: http://cloudradar-cnsh.darwin.hk:27075
  - name: "#订阅# CS:GO Premium"
    url: https://prd-status-csgo-premium.check.darwin.hk
  - name: "#订阅# CS:GO CloudRadar"
    url: https://prd-status-csgo-cloudradar.check.darwin.hk
  - name: "#订阅# PUBG Premium"
    url: https://prd-status-pubg-premium.check.darwin.hk


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.darwin.hk
  # baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: 达尔文服务实时状态
  introTitle: "**服务状态**"
  introMessage: "**达尔文DARWIN** 线上服务实时状态"
  navbar:
    - title: 控制台
      href: https://dash.darwin.hk/
    - title: 购买授权
      href: https://www.darwin.hk/pay.html

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

i18n:
  activeIncidents: Active Incidents
  allSystemsOperational: "全部服务都在线"
  incidentReport: "Incident #$NUMBER report →"
  activeIncidentSummary: Opened at $DATE with $POSTS posts
  incidentTitle: Incident $NUMBER Details
  incidentDetails: Incident Details
  incidentFixed: Fixed
  incidentOngoing: Ongoing
  incidentOpenedAt: Opened at
  incidentClosedAt: Closed at
  incidentSubscribe: Subscribe to Updates
  incidentViewOnGitHub: View on GitHub
  incidentCommentSummary: Posted at $DATE by $AUTHOR
  incidentBack: ← Back to all incidents
  pastIncidents: Past Incidents
  pastIncidentsResolved: Resolved in $MINUTES minutes with $POSTS posts
  liveStatus: "实时状态"
  overallUptime: "总体正常运行时间: $UPTIME"
  overallUptimeTitle: "总体正常运行"
  averageResponseTime: "平均响应时间: $TIMEms"
  averageResponseTimeTitle: "平均响应"
  sevelDayResponseTime: "最近一周的响应时间"
  responseTimeMs: "响应时间 (毫秒)"
  up: "正常"
  down: "离线"
  degraded: "异常"
  ms: "毫秒"
  loading: "加载中"
  navGitHub: GitHub
  footer: "[达尔文DARWIN](https://www.darwin.hk)实时服务状态, 可能存在1-5分钟的数据延迟。"
  rateLimitExceededTitle: Rate limit exceedeed
  rateLimitExceededIntro: You have exceeded the number of requests you can do in an hour, so you'll have to wait before accessing this website again. Alternately, you can add a GitHub Personal Access Token to continue to use this website.
  rateLimitExceededWhatDoesErrorMean: What does this error mean?
  rateLimitExceededErrorMeaning: This website uses the GitHub API to access real-time data about our websites' status. By default, GitHub allows each IP address 60 requests per hour, which you have consumed.
  rateLimitExceededErrorHowCanFix: How can I fix it?
  rateLimitExceededErrorFix: You can wait for another hour and your IP address' limit will be restored. Alternately, you can add your GitHub Personal Access Token, which gives you an additional 5,000 requests per hour.
rateLimitExceededGeneratePAT: Learn how to generate a Personal Access Token
rateLimitExceededHasSet: You have a personal access token set.
rateLimitExceededRemoveToken: Remove token
rateLimitExceededGitHubPAT: GitHub Personal Access Token
rateLimitExceededCopyPastePAT: Copy and paste your token
rateLimitExceededSaveToken: Save token
errorTitle: An error occurred
errorIntro: An error occurred in trying to get the latest status details.
errorText: You can try again in a few moments.
errorHome: Go to the homepage
pastScheduledMaintenance: Past Scheduled Maintenance
scheduledMaintenance: Scheduled Maintenance
scheduledMaintenanceSummaryStarted: Started at $DATE for $DURATION minutes
scheduledMaintenanceSummaryStarts: Starts at $DATE for $DURATION minutes
startedAt: "已经开始于"
startsAt: "开始于"
duration: "持续"
durationMin: "$DURATION 分钟"
incidentCompleted: "已完成"
incidentScheduled: "已计划"
